#!/bin/bash

# index: 0
# name: <alsa_output.usb-Sennheiser_Sennheiser_SCx5_USB_MS_5698120436064112-00.iec958-stereo>
# index: 1
# name: <alsa_output.pci-0000_00_1b.0.analog-stereo>

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

if [ -z $1 ]
then
    pacmd list-sinks | grep -e 'name:' -e 'index:'
    printf "\n\n${Green} audio_out speaker ${Color_Off} to set speakers as output device\n"
    printf "${Green} audio_out headset ${Color_Off} to set headset as output device\n"
    exit
fi


if [ $1 == 'speaker' ]
then
    pacmd "set-default-sink alsa_output.pci-0000_00_1b.0.analog-stereo"

elif [ $1 == 'headset' ] 
then
    pacmd "set-default-sink alsa_output.usb-Sennheiser_Sennheiser_SCx5_USB_MS_5698120436064112-00.iec958-stereo"
fi
